apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
  labels:
    component: mutating-controller
webhooks:
  - name: mutate.default.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    rules:
      - apiGroups: [""]
        resources:
          - "deployments"
        apiVersions:
          - "*"
        operations:
          - CREATE
    clientConfig:
      service:
        name: mutate
        namespace: default
        path: /mutate/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVLRENDQXhDZ0F3SUJBZ0lVSUgyaWFrckFTMml4NEU5NjRLdmQrbUtDRDBzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daTXhDekFKQmdOVkJBWVRBa0pTTVJJd0VBWURWUVFJREFsVFlXOGdVR0YxYkc4eEVqQVFCZ05WQkFjTQpDVk5oYnlCUVlYVnNiekVOTUFzR0ExVUVDZ3dFVkdWemRERVFNQTRHQTFVRUN3d0hWR1Z6ZEdsdVp6RVJNQThHCkExVUVBd3dJYldGdWFXeHpiMjR4S0RBbUJna3Foa2lHOXcwQkNRRVdHV0Z1ZEc5dWFXOXNkWE56WVhScE9VQm4KYldGcGJDNWpiMjB3SGhjTk1qSXdNekF6TURJME5USXpXaGNOTWpReE1qSXhNREkwTlRJeldqQ0JrekVMTUFrRwpBMVVFQmhNQ1FsSXhFakFRQmdOVkJBZ01DVk5oYnlCUVlYVnNiekVTTUJBR0ExVUVCd3dKVTJGdklGQmhkV3h2Ck1RMHdDd1lEVlFRS0RBUlVaWE4wTVJBd0RnWURWUVFMREFkVVpYTjBhVzVuTVJFd0R3WURWUVFEREFodFlXNXAKYkhOdmJqRW9NQ1lHQ1NxR1NJYjNEUUVKQVJZWllXNTBiMjVwYjJ4MWMzTmhkR2s1UUdkdFlXbHNMbU52YlRDQwpBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUxDemQya01CbUZoU2t0T05DdUtOYU41CnpHLzgyVE01TDJ4VzdNOHpPYjhzaCtYSS9TYjJneU82ODBOMWFIL295NnVjVThDUXU5TTUzME5GejZRbklkWFAKcGNZT2lZSHovczNRSUtXSll2QXB1bGd1SXd5QW1DWUVVdXBsdmRVS08yVmFhakhnanNMSFpGU0JUdFp6YlRDbApsY3FLRWVlVXFGeUkwNlNBRS8wUVZtbXo4dFphREptYWIyYlZ4VkQvTlB5cUpRWjgzMTY3aG8zMVc1WEtUa3pjCmFUTm5zUk5uelR1amFjenlMam95V0paSjVPVDFCQ3JKNnBENDZqa0VoZEVuN2ZzY0k1QXJHSkVqWE03MVJiWVYKajhMRFdUSldpWnFjV1RYUVp6QkJ4T1BWeXFGVGR6ODQ1YUx5T2xrMHdZbzlKYjcrOWszMXBUSXE1SUEwbVpNQwpBd0VBQWFOeU1IQXdIUVlEVlIwT0JCWUVGSjg4THVFNDF0MUw5aktzNnNVZW5aQ1p3enpmTUI4R0ExVWRJd1FZCk1CYUFGSjg4THVFNDF0MUw5aktzNnNVZW5aQ1p3enpmTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSMFIKQkJZd0ZJSVNiWFYwWVhSbExtUmxabUYxYkhRdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUF1WkZmeQo2L29yMGF4a2c4U1puYVpCYWlxQ1RZNDk2b0FaN0VEUTd5RzFHc3VMMmRIa1JSd3ppMUE3b2Nld3ZVQkFhY0crCjZOZkZKWnR4N0E1Z0VMWEtKNzBxcEFMbFlSSHIrRWlZWFZSbW94NlVabEN4S3Buc0MxejhZUGFVSFFPZ08wZ1YKWTFGTEZUbDZNcS9RVFNJdCtCZVBndTREVlFEK3U4ZmtxOGpZelZZdzdLOWxHems3NG92enMyVWNIdnljSTdsZwpDSXdsRjUxMGowVmFoNUxDWDZhZFptc1FTdEVVanJ0K21EdzF5MlFaUHVOL2tFdzBBdC9aczdhK3lCeVlLclNaCjhPN3pEM1RPRFE0THVOZmtwSWdqRVNqN0VhZVFiZkw5dVhmZ0pyMVZXaDB1Q0xIVTJhVE8vVGFJWklWbGtHVDkKcFFMaEJWRXhycG1ZcURFRAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==